services:
  db:
    restart: always

  directus:
    restart: unless-stopped
    ports:
      - "9001:8055"
    environment:
      SLK_ENV: production

  frontend:
    restart: unless-stopped
    ports:
      - "9000:3000"
    environment:
      SLK_ENV: production

