services:
  db:
    restart: always

  directus:
    restart: unless-stopped
    user: "${UID}:${GID}"
    ports:
      - "9001:8055"

  frontend:
    restart: unless-stopped
    user: "${UID}:${GID}"
    ports:
      - "9000:3000"
