services:
  db:
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  directus:
    ports:
      - "8081:8055"
    command: ["sh", "/start_dev.sh"]

  frontend:
    ports:
      - "8080:3000"
      - "24678:24678"
    command: ["sh", "/start_dev.sh"]
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./pgadmin:/pgadmin

volumes:
  db-data:
    driver: local
