collection: election_config
field: cutoff_date
type: dateTime
meta:
  collection: election_config
  conditions: null
  display: null
  display_options: null
  field: cutoff_date
  group: null
  hidden: false
  interface: datetime
  note: null
  options: null
  readonly: false
  required: false
  sort: 3
  special: null
  translations:
    - language: de-DE
      translation: Stichtag (Cutoff Date)
  validation: null
  validation_message: null
  width: half
schema:
  name: cutoff_date
  table: election_config
  data_type: timestamp without time zone
  default_value: null
  max_length: null
  numeric_precision: null
  numeric_scale: null
  is_nullable: true
  is_unique: false
  is_primary_key: false
  is_generated: false
  generation_expression: null
  has_auto_increment: false
  foreign_key_table: null
  foreign_key_column: null
