<template>
  <div :id="`step-${step.index}`" class="scroll-mt-32 py-8 border-b border-gray-100 last:border-b-0">
    <!-- Step header -->
    <div class="mb-6">
      <div class="flex items-center gap-2 mb-2">
        <span class="w-6 h-6 rounded-full bg-[#006e94]/10 text-[#006e94] flex items-center justify-center text-xs font-bold flex-none">
          {{ step.index + 1 }}
        </span>
        <h3 class="font-semibold text-gray-900 text-base leading-snug">{{ t(step.title) }}</h3>
      </div>
      <p v-if="t(step.description)" class="text-sm text-gray-600 leading-relaxed pl-8">
        {{ t(step.description) }}
      </p>
    </div>

    <!-- Layout: kpi_map — KPI left (40%) + Vega map right (60%), or full DataProductPanel if no useful map -->
    <div v-if="step.layout === 'kpi_map' && mapElement" class="grid grid-cols-5 gap-4 items-start">
      <div class="col-span-2">
        <DataProductPanel
          v-if="kpiCollection"
          :collection="kpiCollection"
          :ars="ars"
          :base-url="baseUrl"
          :population="population"
          :hide-map="true"
        />
      </div>
      <div class="col-span-3" style="height: 340px">
        <ClientOnly>
          <VegaChart :spec="mapSpec" />
        </ClientOnly>
      </div>
    </div>
    <div v-else-if="step.layout === 'kpi_map'">
      <DataProductPanel
        v-if="kpiCollection"
        :collection="kpiCollection"
        :ars="ars"
        :base-url="baseUrl"
        :population="population"
      />
    </div>

    <!-- Layout: full_width — single chart spanning full width -->
    <div v-else-if="step.layout === 'full_width' && primarySpec" class="w-full" style="height: 360px">
      <ClientOnly>
        <VegaChart :spec="primarySpec" />
      </ClientOnly>
    </div>
    <!-- full_width with no spec yet (e.g. timeseries not yet generated by backend) -->
    <div v-else-if="step.layout === 'full_width'" class="py-6 text-sm text-gray-400 italic">
      Visualisierung für diesen Schritt noch nicht verfügbar.
    </div>

    <!-- Layout: split — two equal charts side by side -->
    <div v-else-if="step.layout === 'split'" class="grid grid-cols-2 gap-4" style="height: 300px">
      <ClientOnly>
        <VegaChart
          v-for="el in step.elements.filter(e => e.vegalite_spec)"
          :key="el.plot_id"
          :spec="injectArea(el.vegalite_spec, ars)"
        />
      </ClientOnly>
    </div>

    <!-- Layout: image_text — image left (50%) + description right (50%) -->
    <div v-else-if="step.layout === 'image_text'" class="grid grid-cols-2 gap-6 items-start">
      <div class="rounded-lg overflow-hidden bg-gray-100">
        <img
          v-if="imageElement?.src_url"
          :src="imageElement.src_url"
          :alt="t(imageElement.title)"
          class="w-full h-auto object-cover"
        />
        <div v-else class="h-48 flex items-center justify-center text-gray-400 text-sm">
          Kein Bild verfügbar
        </div>
      </div>
      <div class="text-sm text-gray-600 leading-relaxed">
        {{ t(step.description) }}
      </div>
    </div>

    <!-- Layout: default — DataProductPanel for all elements -->
    <div v-else>
      <DataProductPanel
        v-if="kpiCollection"
        :collection="kpiCollection"
        :ars="ars"
        :base-url="baseUrl"
        :population="population"
      />
      <!-- Extra non-KPI vega elements in this step -->
      <template v-for="el in nonKpiVegaElements" :key="el.plot_id">
        <div class="w-full mt-4" style="height: 280px">
          <ClientOnly>
            <VegaChart :spec="injectArea(el.vegalite_spec, ars)" />
          </ClientOnly>
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { ResolvedStep } from '~/composables/useCollectionRender'
import type { Collection } from '~/types/slz-api'
import { useSlzLocale } from '~/composables/useSlzLocale'

const props = defineProps<{
  step: ResolvedStep
  collection: Collection
  ars: string
  baseUrl: string
  population?: number | null
}>()

const { t } = useSlzLocale()

// Inject ?area=ARS into every data.url in a Vega-Lite spec (handles layer specs too)
function injectArea(spec: object | null | undefined, ars: string): object | null {
  if (!spec || !ars) return spec ?? null
  const s = JSON.parse(JSON.stringify(spec))
  function patchUrl(node: any) {
    if (node?.data?.url) {
      try {
        const u = new URL(node.data.url)
        u.searchParams.set('area', ars)
        node.data.url = u.toString()
      } catch {}
    }
    if (Array.isArray(node?.layer)) node.layer.forEach(patchUrl)
  }
  patchUrl(s)
  return s
}

// Build a synthetic collection scoped to this step's elements for DataProductPanel
const kpiCollection = computed((): Collection => ({
  ...props.collection,
  render_elements: props.step.elements,
}))

const primaryElement = computed(() => props.step.elements[0] ?? null)

// primary element's Vega spec with area injected (for full_width / split)
const primarySpec = computed(() =>
  primaryElement.value?.vegalite_spec
    ? injectArea(primaryElement.value.vegalite_spec as object, props.ars)
    : null
)

const mapElement = computed(() =>
  props.step.elements.find(e => e.type === 'map' && e.vegalite_spec) ?? null
)

// map spec with area injected
const mapSpec = computed(() =>
  mapElement.value ? injectArea(mapElement.value.vegalite_spec as object, props.ars) : null
)

const imageElement = computed(() =>
  props.step.elements.find(e => e.type === 'image') ?? null
)

const nonKpiVegaElements = computed(() =>
  props.step.elements.filter(e => e.type !== 'kpi' && e.vegalite_spec)
)
</script>
