<template>
  <div :id="`step-${step.index}`" class="border-gray-100 scroll-mt-32 border-b py-8 last:border-b-0">
    <!-- Step header -->
    <div class="mb-6">
      <div class="mb-2 flex items-center gap-2">
        <span
          class="flex h-6 w-6 flex-none items-center justify-center rounded-full bg-[#006e94]/10 text-xs font-bold text-[#006e94]"
        >
          {{ step.index + 1 }}
        </span>
        <h3 class="text-gray-900 text-base font-semibold leading-snug">{{ t(step.title) }}</h3>
      </div>
      <p v-if="t(step.description)" class="text-gray-600 pl-8 text-sm leading-relaxed">
        {{ t(step.description) }}
      </p>
    </div>

    <!-- Layout: kpi_map — KPI left (40%) + Vega map right (60%) -->
    <div v-if="step.layout === 'kpi_map' && mapElement && kpiElement" class="grid grid-cols-5 items-start gap-4">
      <div class="col-span-2">
        <KPICard
          :element="kpiElement"
          :collection-slug="collection.id"
          :ars="ars"
          :base-url="baseUrl"
          :population="population"
        />
      </div>
      <div class="col-span-3" style="height: 340px">
        <ClientOnly>
          <VegaChart
            :spec="mapSpec"
            :export-area-name="areaName"
            :export-ars="ars"
            :export-title="localizedElementTitle(mapElement) || stepTitle"
            :export-subtitle="localizedElementDescription(mapElement) || stepDescription"
            :export-collection-name="collectionTitle"
            :export-updated-at="exportUpdatedAt"
            :export-attribution="exportAttribution"
          />
        </ClientOnly>
      </div>
    </div>
    <!-- kpi_map with no map: fall back to KPICard alone -->
    <div v-else-if="step.layout === 'kpi_map' && kpiElement">
      <KPICard
        :element="kpiElement"
        :collection-slug="collection.id"
        :ars="ars"
        :base-url="baseUrl"
        :population="population"
      />
    </div>
    <!-- kpi_map with no KPI element: full DataProductPanel fallback -->
    <div v-else-if="step.layout === 'kpi_map'">
      <DataProductPanel
        v-if="kpiCollection"
        :collection="kpiCollection"
        :ars="ars"
        :base-url="baseUrl"
        :population="population"
        :municipality-name="areaName"
        :export-updated-at="exportUpdatedAt"
        :export-attribution="exportAttribution"
      />
    </div>

    <!-- Layout: full_width — single chart spanning full width -->
    <div v-else-if="step.layout === 'full_width' && primarySpec" class="w-full" style="height: 360px">
      <ClientOnly>
        <VegaChart
          :spec="primarySpec"
          :export-area-name="areaName"
          :export-ars="ars"
          :export-title="localizedElementTitle(primaryElement) || stepTitle"
          :export-subtitle="localizedElementDescription(primaryElement) || stepDescription"
          :export-collection-name="collectionTitle"
          :export-updated-at="exportUpdatedAt"
          :export-attribution="exportAttribution"
        />
      </ClientOnly>
    </div>
    <!-- full_width with no spec yet (e.g. timeseries not yet generated by backend) -->
    <div v-else-if="step.layout === 'full_width'" class="text-gray-400 py-6 text-sm italic">
      Visualisierung für diesen Schritt noch nicht verfügbar.
    </div>

    <!-- Layout: split — two equal charts side by side -->
    <div v-else-if="step.layout === 'split'" class="grid grid-cols-2 gap-4" style="height: 300px">
      <ClientOnly>
        <VegaChart
          v-for="el in step.elements.filter((e) => e.vegalite_spec)"
          :key="el.plot_id"
          :spec="injectArea(el.vegalite_spec, ars)"
          :export-area-name="areaName"
          :export-ars="ars"
          :export-title="localizedElementTitle(el) || stepTitle"
          :export-subtitle="localizedElementDescription(el) || stepDescription"
          :export-collection-name="collectionTitle"
          :export-updated-at="exportUpdatedAt"
          :export-attribution="exportAttribution"
        />
      </ClientOnly>
    </div>

    <!-- Layout: image_text — image left (50%) + description right (50%) -->
    <div v-else-if="step.layout === 'image_text'" class="grid grid-cols-2 items-start gap-6">
      <DataImage v-if="imageElement" :element="imageElement" :collection-slug="collection.id" :base-url="baseUrl" />
      <div v-else class="bg-gray-100 text-gray-400 flex h-48 items-center justify-center rounded-lg text-sm">
        Kein Bild verfügbar
      </div>
      <div class="text-gray-600 text-sm leading-relaxed">
        {{ t(step.description) }}
      </div>
    </div>

    <!-- Layout: default — DataProductPanel for all elements -->
    <div v-else>
      <DataProductPanel
        v-if="kpiCollection"
        :collection="kpiCollection"
        :ars="ars"
        :base-url="baseUrl"
        :population="population"
        :municipality-name="areaName"
        :export-updated-at="exportUpdatedAt"
        :export-attribution="exportAttribution"
      />
      <!-- Extra non-KPI vega elements in this step -->
      <template v-for="el in nonKpiVegaElements" :key="el.plot_id">
        <div class="mt-4 w-full" style="height: 280px">
          <ClientOnly>
            <VegaChart
              :spec="injectArea(el.vegalite_spec, ars)"
              :export-area-name="areaName"
              :export-ars="ars"
              :export-title="localizedElementTitle(el) || stepTitle"
              :export-subtitle="localizedElementDescription(el) || stepDescription"
              :export-collection-name="collectionTitle"
              :export-updated-at="exportUpdatedAt"
              :export-attribution="exportAttribution"
            />
          </ClientOnly>
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import type { ResolvedStep } from "~/composables/useCollectionRender";
import type { Collection } from "~/types/slz-api";
import { useSlzLocale } from "~/composables/useSlzLocale";

const props = defineProps<{
  step: ResolvedStep;
  collection: Collection;
  ars: string;
  baseUrl: string;
  population?: number | null;
  areaName?: string;
  exportUpdatedAt?: string;
  exportAttribution?: string;
}>();

const { t } = useSlzLocale();
const collectionTitle = computed(() => t(props.collection.title) || props.collection.id);
const stepTitle = computed(() => t(props.step.title) || collectionTitle.value);
const stepDescription = computed(() => t(props.step.description));

function localizedElementTitle(element: any) {
  return t(element?.title);
}

function localizedElementDescription(element: any) {
  return t(element?.description);
}

// Inject ?area=ARS into every data.url in a Vega-Lite spec (handles layer specs too)
function injectArea(spec: object | null | undefined, ars: string): object | null {
  if (!spec || !ars) return spec ?? null;
  const s = JSON.parse(JSON.stringify(spec));
  function patchUrl(node: any) {
    if (node?.data?.url) {
      try {
        const u = new URL(node.data.url);
        u.searchParams.set("area", ars);
        node.data.url = u.toString();
      } catch {}
    }
    if (Array.isArray(node?.layer)) node.layer.forEach(patchUrl);
  }
  patchUrl(s);
  return s;
}

// Build a synthetic collection scoped to this step's elements for DataProductPanel
const kpiCollection = computed(
  (): Collection => ({
    ...props.collection,
    render_elements: props.step.elements,
  }),
);

const primaryElement = computed(() => props.step.elements[0] ?? null);

// primary element's Vega spec with area injected (for full_width / split)
const primarySpec = computed(() =>
  primaryElement.value?.vegalite_spec ? injectArea(primaryElement.value.vegalite_spec as object, props.ars) : null,
);

const mapElement = computed(() => props.step.elements.find((e) => e.type === "map" && e.vegalite_spec) ?? null);

// map spec with area injected
const mapSpec = computed(() =>
  mapElement.value ? injectArea(mapElement.value.vegalite_spec as object, props.ars) : null,
);

const kpiElement = computed(() => props.step.elements.find((e) => e.type === "kpi") ?? null);

const imageElement = computed(() => props.step.elements.find((e) => e.type === "image") ?? null);

const nonKpiVegaElements = computed(() => props.step.elements.filter((e) => e.type !== "kpi" && e.vegalite_spec));
</script>
