name: EditorLocalteam
icon: supervised_user_circle
description: Reguläres Mitglied eines Lokalteams
children:
  - AdminLokalteam
policies:
  - App-Zugriff-Minimum
  - Erfolgsprojekte-Contributor
  - Lokalteam-Bewertung
  - Lokalteam-Mitglied
  - Lokalteam-Wahlcheck
  - Public
