name: frontend
icon: web_asset
description: null
ip_access: null
enforce_tfa: false
admin_access: false
app_access: false
permissions:
  - collection: ratings_measures
    action: read
    permissions:
      _and:
        - status:
            _eq: published
        - approved:
            _eq: true
        - measure_id:
            status:
              _eq: published
    validation: null
    presets: null
    fields:
      - applicable
      - rating
      - localteam_id
      - measure_id
      - id
      - sort
      - Source
      - source
      - achievement
      - current_progress
      - date_updated
      - why_not_applicable
  - collection: pages
    action: read
    permissions:
      _and:
        - status:
            _eq: published
    validation: null
    presets: null
    fields:
      - id
      - menus
      - slug
      - sort
      - sort_order
      - footer_column_desktop
      - is_dynamic
      - translations
  - collection: pages_translations
    action: read
    permissions: null
    validation: null
    presets: null
    fields:
      - languages_code
      - name
      - contents
  - collection: municipalities
    action: read
    permissions: null
    validation: null
    presets: null
    fields:
      - sort
      - slug
      - municipality_type
      - details
      - score_cpma
      - score_iec
      - score_transport
      - scores
      - mayor
      - state
      - population
      - party_mayor
      - score_energy
      - score_total
      - score_ann
      - score_bh
      - place
      - localteam_id
      - date_updated
      - status
      - overall_status_comment
      - public_contact
      - geolocation
      - percentage_rated
  - collection: municipalities_translations
    action: read
    permissions: null
    validation: null
    presets: null
    fields:
      - languages_code
      - name
      - description
  - collection: measures
    action: read
    permissions:
      _and:
        - status:
            _eq: published
    validation: null
    presets: null
    fields:
      - id
      - sort
      - sector
      - slug
      - impact
      - weight
      - feasibility_political
      - feasibility
      - feasibility_economical
      - description
      - date_updated
      - measure_id
      - translations
  - collection: measures_translations
    action: read
    permissions: null
    validation: null
    presets: null
    fields:
      - name
      - verification_description
      - notes
      - description
      - accordion_p4jgb8
      - description_evaluation_criteria
      - description_about
      - description_benefit
      - description_verification
      - description_contribution
      - description_implementation
      - description_legal
      - description_funding
      - description_tutorial
  - collection: directus_translations
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: articles
    action: read
    permissions:
      _and:
        - status:
            _eq: published
    validation: {}
    presets: null
    fields:
      - status
      - title
      - slug
      - date_updated
      - author
      - date_created
      - municipality_name
      - state
      - content
      - subtitle
      - image
      - image_credits
      - abstract
      - article_text
      - organisation
      - link
      - sectors
      - sources
      - qualities
      - ease_of_implementation
      - similar_external_projects
      - similar_articles
      - impact
      - id
      - additional_examples
      - economic_efficiency
      - public_impact
      - ghg_savings_potential
      - other_benefits
      - additional_infos
      - can_do_autonomously
      - is_profitable
      - public_impact_effects
      - ghg_savings_level
  - collection: articles_articles
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: articles_external_projects
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: organisations
    action: read
    permissions: null
    validation: null
    presets: null
    fields:
      - name
      - link
      - short_description
      - logo
      - id
  - collection: feedback
    action: create
    permissions: null
    validation: null
    presets: null
    fields:
      - title
      - content
      - type
      - sender_name
      - sender_contact
      - date_created
      - status
  - collection: languages
    action: read
    permissions:
      _and:
        - status:
            _eq: published
    validation: null
    presets: null
    fields:
      - code
      - name
      - flag
