name: frontend
icon: web_asset
description: null
ip_access: null
enforce_tfa: false
admin_access: false
app_access: false
permissions:
  - collection: articles
    action: read
    permissions:
      _and:
        - status:
            _eq: published
    validation: {}
    presets: null
    fields:
      - status
      - title
      - slug
      - date_updated
      - author
      - date_created
      - municipality_name
      - state
      - content
      - subtitle
      - image
      - image_credits
      - abstract
      - article_text
      - organisation
      - link
      - sectors
      - sources
      - qualities
      - ease_of_implementation
      - similar_external_projects
      - similar_articles
      - impact
      - id
      - additional_examples
      - economic_efficiency
      - public_impact
      - ghg_savings_potential
      - other_benefits
      - additional_infos
      - can_do_autonomously
      - is_profitable
      - public_impact_effects
      - ghg_savings_level
      - content_segment
      - social_media
      - instagram
      - linkedin
      - additional_infos_segment
      - ease_of_implementation_block
      - economic_efficiency_block
      - public_impact_block
      - ghg_savings_potential_block
      - other_benefits_block
      - similar_projects_segment
  - collection: articles_articles
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: articles_external_projects
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: directus_translations
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: external_projects
    action: read
    permissions: null
    validation: null
    presets: null
    fields:
      - id
      - description
      - title
      - link
      - date_updated
      - date_created
  - collection: feedback
    action: create
    permissions: null
    validation: null
    presets: null
    fields:
      - title
      - content
      - type
      - sender_name
      - sender_contact
      - date_created
      - status
  - collection: localteams
    action: read
    permissions: null
    validation: null
    presets: null
    fields:
      - id
      - municipality_id
      - status
      - municipality_name
      - slug
      - name
  - collection: measure_catalog
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: measures
    action: read
    permissions:
      _and:
        - status:
            _eq: published
        - catalog_version:
            hidden:
              _eq: false
    validation: null
    presets: null
    fields:
      - id
      - sort
      - name
      - sector
      - slug
      - impact
      - weight
      - feasibility_political
      - feasibility
      - feasibility_economical
      - verification_description
      - notes
      - description
      - date_updated
      - accordion-p4jgb8
      - description_evaluation_criteria
      - description_about
      - description_benefit
      - description_verification
      - description_contribution
      - description_implementation
      - description_legal
      - description_funding
      - description_tutorial
      - measure_id
      - catalog_version
      - must_be_rated_again
      - choices_rating
  - collection: municipalities
    action: read
    permissions: null
    validation: null
    presets: null
    fields:
      - sort
      - slug
      - municipality_type
      - details
      - scores
      - mayor
      - state
      - population
      - party_mayor
      - name
      - description
      - localteam_id
      - date_updated
      - status
      - overall_status_comment
      - public_contact
      - ars
      - geolocation
      - percentage_rated
      - id
  - collection: municipality_scores
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: organisations
    action: read
    permissions: null
    validation: null
    presets: null
    fields:
      - name
      - link
      - short_description
      - logo
      - id
      - instagram
      - linkedin
      - social_media_segment
  - collection: pages
    action: read
    permissions:
      _and:
        - status:
            _eq: published
    validation: null
    presets: null
    fields:
      - id
      - name
      - menus
      - contents
      - slug
      - sort
      - sort_order
      - footer_column_desktop
      - is_dynamic
      - icon_svg
  - collection: ratings_measures
    action: read
    permissions:
      _and:
        - status:
            _eq: published
        - approved:
            _eq: true
        - measure_id:
            status:
              _eq: published
        - measure_id:
            catalog_version:
              hidden:
                _eq: false
    validation: null
    presets: null
    fields:
      - applicable
      - rating
      - localteam_id
      - measure_id
      - id
      - sort
      - Source
      - source
      - achievement
      - current_progress
      - date_updated
      - why_not_applicable
      - status
      - measure_published
