name: PartnerAPI
icon: volunteer_activism
description: Access to parts of our API for partners
ip_access: null
enforce_tfa: false
admin_access: false
app_access: false
permissions:
  - collection: articles
    action: read
    permissions:
      _and:
        - status:
            _eq: published
    validation: null
    presets: null
    fields:
      - id
      - title
      - status
      - slug
      - date_updated
      - date_created
      - author
      - municipality_name
      - state
      - content
      - image
      - subtitle
      - image_credits
      - abstract
      - organisation
      - article_text
      - link
  - collection: organisations
    action: read
    permissions: null
    validation: null
    presets: null
    fields:
      - id
      - name
      - link
      - short_description
      - logo
  - collection: municipalities
    action: read
    permissions: null
    validation: null
    presets: null
    fields:
      - id
      - status
      - name
      - municipality_type
      - details
      - description
      - state
      - population
      - mayor
      - party_mayor
      - geolocation
      - slug
