name: Planungsteam
icon: supervised_user_circle
description: null
ip_access: null
enforce_tfa: false
admin_access: false
app_access: true
permissions:
  - collection: directus_files
    action: create
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_files
    action: read
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_files
    action: update
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_files
    action: delete
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_dashboards
    action: create
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_dashboards
    action: read
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_dashboards
    action: update
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_dashboards
    action: delete
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_panels
    action: create
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_panels
    action: read
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_panels
    action: update
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_panels
    action: delete
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_folders
    action: create
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_folders
    action: read
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_folders
    action: update
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_folders
    action: delete
    permissions: {}
    validation: null
    presets: null
    fields: null
  - collection: directus_users
    action: read
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_users
    action: update
    permissions:
      id:
        _eq: $CURRENT_USER
    validation: null
    presets: null
    fields:
      - first_name
      - last_name
      - email
      - password
      - location
      - title
      - description
      - avatar
      - language
      - appearance
      - theme_light
      - theme_dark
      - theme_light_overrides
      - theme_dark_overrides
      - tfa_secret
  - collection: directus_roles
    action: read
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_shares
    action: read
    permissions:
      _or:
        - role:
            _eq: $CURRENT_ROLE
        - role:
            _null: true
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_shares
    action: create
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_shares
    action: update
    permissions:
      user_created:
        _eq: $CURRENT_USER
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_shares
    action: delete
    permissions:
      user_created:
        _eq: $CURRENT_USER
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_flows
    action: read
    permissions:
      trigger:
        _eq: manual
    validation: null
    presets: null
    fields:
      - id
      - status
      - name
      - icon
      - color
      - options
      - trigger
  - collection: articles
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: editors
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: feedback
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: junction_directus_users_localteams
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: localteams
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: measures
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: municipalities
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: organisations
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: pages
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: ratings_measures
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: feedback
    action: update
    permissions: null
    validation: null
    presets: null
    fields:
      - status
      - internal_response_summary
