name: Public
description: Unauthenticated access
permissions:
  - collection: directus_files
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: blocks
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: pages
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: navigation_config
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: news_items
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: events
    action: read
    permissions:
      _and:
        - status:
            _eq: published
    validation: null
    presets: null
    fields:
      - id
      - slug
      - title
      - description
      - event_type
      - status
      - start_date
      - end_date
      - location
      - registration_url
      - date_created
      - image
  - collection: municipalities
    action: read
    permissions: null
    validation: null
    presets: null
    fields:
      - sort
      - slug
      - municipality_type
      - details
      - scores
      - mayor
      - state
      - population
      - party_mayor
      - name
      - description
      - localteam_id
      - date_updated
      - status
      - overall_status_comment
      - public_contact
      - ars
      - geolocation
      - percentage_rated
      - id
      - creator_verified
      - preview_token
      - image
  - collection: measures
    action: read
    permissions:
      _and:
        - status:
            _eq: published
    validation: null
    presets: null
    fields:
      - id
      - sort
      - sector
      - slug
      - impact
      - weight
      - feasibility_political
      - feasibility
      - feasibility_economical
      - description
      - date_updated
      - measure_id
      - catalog_version
      - translations
  - collection: measures_translations
    action: read
    permissions: null
    validation: null
    presets: null
    fields:
      - name
      - verification_description
      - notes
      - description
      - accordeon_p4jgb8
      - description_evaluation_criteria
      - description_about
      - description_benefit
      - description_verification
      - description_contribution
      - description_implementation
      - description_legal
      - description_funding
      - description_tutorial
  - collection: languages
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: pages_translations
    action: read
    permissions: null
    validation: null
    presets: null
    fields:
      - languages_code
      - name
      - contents
  - collection: directus_translations
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
