name: Public
description: Unauthenticated access
permissions:
  - collection: directus_files
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: blocks
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: pages
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: navigation_config
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: news_items
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
