name: Public
description: Unauthenticated access
permissions:
  - collection: directus_files
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: pages
    action: read
    permissions:
      _and:
        - status:
            _eq: published
    validation: {}
    presets: null
    fields:
      - id
      - name
      - menus
      - contents
      - slug
      - sort
      - sort_order
      - page_category
      - is_dynamic
      - icon_svg
  - collection: blocks
    action: read
    permissions:
      _and:
        - status:
            _eq: published
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: navigation_config
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
