name: StatisticsAPI
icon: supervised_user_circle
description: null
ip_access: null
enforce_tfa: false
admin_access: false
app_access: false
permissions:
  - collection: articles
    action: create
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: articles
    action: delete
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: articles
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: articles
    action: update
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: articles_articles
    action: create
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: articles_articles
    action: delete
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: articles_articles
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: articles_articles
    action: update
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: articles_external_projects
    action: create
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: articles_external_projects
    action: delete
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: articles_external_projects
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: articles_external_projects
    action: update
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: directus_dashboards
    action: create
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_dashboards
    action: delete
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_dashboards
    action: read
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_dashboards
    action: update
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_files
    action: create
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_files
    action: delete
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_files
    action: read
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_files
    action: update
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_flows
    action: read
    permissions:
      trigger:
        _eq: manual
    validation: null
    presets: null
    fields:
      - id
      - status
      - name
      - icon
      - color
      - options
      - trigger
  - collection: directus_folders
    action: create
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_folders
    action: delete
    permissions: {}
    validation: null
    presets: null
    fields: null
  - collection: directus_folders
    action: read
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_folders
    action: update
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_panels
    action: create
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_panels
    action: delete
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_panels
    action: read
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_panels
    action: update
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: directus_roles
    action: read
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - collection: editors
    action: create
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: editors
    action: delete
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: editors
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: editors
    action: update
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: external_projects
    action: create
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: external_projects
    action: delete
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: external_projects
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: external_projects
    action: update
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: feedback
    action: create
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: feedback
    action: delete
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: feedback
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: feedback
    action: update
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: junction_directus_users_localteams
    action: create
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: junction_directus_users_localteams
    action: delete
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: junction_directus_users_localteams
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: junction_directus_users_localteams
    action: update
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: localteams
    action: create
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: localteams
    action: delete
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: localteams
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: localteams
    action: update
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: measures
    action: create
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: measures
    action: delete
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: measures
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: measures
    action: update
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: municipalities
    action: create
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: municipalities
    action: delete
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: municipalities
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: municipalities
    action: update
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: organisations
    action: create
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: organisations
    action: delete
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: organisations
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: organisations
    action: update
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: pages
    action: create
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: pages
    action: delete
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: pages
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: pages
    action: update
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: ratings_measures
    action: create
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: ratings_measures
    action: delete
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: ratings_measures
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: ratings_measures
    action: update
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
