id: 1
project_name: Stadt.Land.Klima
project_url: https://stadt-land-klima.de
project_color: "#2ECDA7"
project_logo: null
public_foreground: null
public_background: null
public_note: null
auth_login_attempts: 25
auth_password_policy: null
storage_asset_transform: all
storage_asset_presets: null
custom_css: null
storage_default_folder: null
basemaps: null
mapbox_key: null
module_bar:
  - type: module
    id: content
    enabled: true
  - type: module
    id: users
    enabled: true
  - type: module
    id: files
    enabled: true
  - type: module
    id: insights
    enabled: true
  - type: module
    id: settings
    enabled: true
    locked: true
project_descriptor: Lokales Klimaschutz-Ranking
default_language: de-DE
custom_aspect_ratios: null
public_favicon: null
default_appearance: auto
default_theme_light: null
theme_light_overrides: null
default_theme_dark: null
theme_dark_overrides: null
