name: CreateEmptyRatings
icon: bolt
color: null
description: Creates an empty rating for the corresponding measure and localteam
status: inactive
trigger: operation
accountability: all
options:
  return: $all
operations:
  - name: Kondition
    key: condition_0odis
    type: condition
    position_x: 20
    position_y: 17
    options:
      filter:
        $last:
          emptyArray:
            _eq: true
    resolve_key: item_create_8neoc
  - name: Skript ausführen
    key: exec_koaij
    type: exec
    position_x: 2
    position_y: 17
    options:
      code: |-
        module.exports = async function(data) {
        	// Do something...
        	return {
            "emptyArray": data["$last"].length===0
        	};
        }
    resolve_key: condition_0odis
  - name: Daten lesen
    key: item_read_68izy
    type: item-read
    position_x: 20
    position_y: 1
    options:
      query:
        filter:
          _and:
            - localteam_id:
                _eq: "{{$last.localteam_id}}"
            - measure_id:
                _eq: "{{$last.measure_id}}"
      collection: ratings_measures
      permissions: $full
    resolve_key: exec_koaij
  - name: Create Data
    key: item_create_8neoc
    type: item-create
    position_x: 3
    position_y: 34
    options:
      collection: ratings_measures
      payload:
        measure_id: "{{$trigger.measure_id}}"
        localteam_id: "{{$trigger.localteam_id}}"
        choices: "{{$trigger.choices}}"
      emitEvents: true
      permissions: $full
operation_key: item_read_68izy
