name: new municipality Trigger CreateEmptyRating
icon: bolt
color: null
description: triggers CreateEmptyRatings for each measures when a new
  municipality is created
status: inactive
trigger: event
accountability: all
options:
  type: action
  scope:
    - items.create
  collections:
    - localteams
operations:
  - name: Run Script
    key: exec_l3jv0
    type: exec
    position_x: 1
    position_y: 19
    options:
      code: |2-
         module.exports = async function(data) {
                    let retData = []
                	for (var i = 0; i < data["$last"].length; i++){
                  		retData.push({
                           "localteam_id":data["$trigger"]["key"],
                       		"measure_id":data["$last"][i]["id"],
                             "choices": data["$last"][i]["choices_rating"]
                        })
                  	}
                    return {retData};
                }
    resolve_key: trigger_i5e2r
  - name: Trigger Flow
    key: trigger_i5e2r
    type: trigger
    position_x: 29
    position_y: 20
    options:
      payload: "{{$last.retData}}"
      flow_name: CreateEmptyRatings
  - name: Read Data
    key: item_read_rlzk6
    type: item-read
    position_x: 19
    position_y: 1
    options:
      collection: measures
      query:
        filter:
          status:
            _eq: published
      permissions: $full
    resolve_key: exec_l3jv0
operation_key: item_read_rlzk6
