name: newMeasure
icon: bolt
color: null
description: triggers CreateEmptyRatings for each localteam  when a new measure
  is created and its status is published
status: inactive
trigger: event
accountability: all
options:
  type: action
  scope:
    - items.create
  collections:
    - measures
operations:
  - name: Read Data
    key: item_read_10gpj
    type: item-read
    position_x: 1
    position_y: 17
    options:
      collection: localteams
      query: null
      permissions: $full
    resolve_key: exec_x1cau
  - name: Run Script
    key: exec_x1cau
    type: exec
    position_x: 22
    position_y: 17
    options:
      code: >2-
         module.exports = async function(data) {
                    let retData = []
                	for (var i = 0; i < data["$last"].length; i++){
                  		retData.push({
                           "localteam_id":data["$last"][i]["id"],
                       		"measure_id": data["$trigger"]["key"],
                            "choices": data["$trigger"]["payload"]["choices_rating"]
                        })
                  	}
                    return {retData};
                }
    resolve_key: trigger_v8atj
  - name: Trigger Flow
    key: trigger_v8atj
    type: trigger
    position_x: 4
    position_y: 36
    options:
      payload: "{{$last.retData}}"
      flow_name: CreateEmptyRatings
  - name: Condition
    key: condition_xau12
    type: condition
    position_x: 22
    position_y: 1
    options:
      filter:
        $trigger:
          payload:
            status:
              _eq: published
    resolve_key: item_read_10gpj
operation_key: condition_xau12
