name: ResetRatingWhenNotApplicable
icon: info
color: null
description: Convenience/UX - when a measure_rating is set as "not applicable",
  change the rating to "not rated" so it doesn't show a rating value in the
  backend overview when disabled
status: active
trigger: event
accountability: all
options:
  type: action
  scope:
    - items.create
    - items.update
  collections:
    - ratings_measures
operations:
  - name: Daten aktualisieren
    key: item_update_xlnjy
    type: item-update
    position_x: 37
    position_y: 1
    options:
      collection: ratings_measures
      payload:
        rating: null
      query:
        filter:
          status:
            _eq: active
      key: "{{$trigger.keys}}"
  - name: Is not applicable
    key: is_not_applicable
    type: condition
    position_x: 19
    position_y: 1
    options:
      filter:
        $trigger:
          payload:
            applicable:
              _eq: false
    resolve_key: item_update_xlnjy
operation_key: is_not_applicable
