name: sendCandidateEmails
icon: email
color: "#2ecc71"
description: Sends personal links to all candidates of a localteam.
status: active
trigger: manual
accountability: all
options:
  requireSelection: false
  accountability: all
  collections:
    - localteams
    - questions
    - candidate
operations:
  - name: Send Candidate Emails
    key: send_candidate_emails_op
    type: operation-send-candidate-emails
    position_x: 10
    position_y: 1
    options: {}
operation_key: send_candidate_emails_op
