name: setCutoffDate
icon: event
color: "#e67e22"
description: Sets the cutoff date for the candidate survey.
status: active
trigger: manual
accountability: all
options:
  requireSelection: false
  collections:
    - localteams
    - questions
    - candidate
  fields:
    - field: cutoff_date
      type: timestamp
      meta:
        interface: datetime
        label: Stichtag
        width: full
  accountability: all
operations:
  - name: Set Cutoff Date
    key: set_cutoff_date_op
    type: operation-set-cutoff-date
    position_x: 10
    position_y: 1
    options:
      cutoff_date: "{{$trigger.data.cutoff_date}}"
operation_key: set_cutoff_date_op
