/** @type {import("tailwindcss").Config} */
module.exports = {
  darkMode: ["class", '[data-theme="staedteChallengeDark"]'],
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./utils/**/*.{js,ts}",
    "./nuxt.config.{js,ts}",
    "./app.vue",
  ],
  theme: {
    extend: {
      screens: {
        xs: "420px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        heading: ["RobotoCondensed", "sans-serif"],
      },
      colors: {
        "rating-4": "#1EA64A",
        "rating-4-light": "#D2EDDB",
        "rating-4-very-light": "#EBF7EF",
        "rating-3": "#AFCA0B",
        "rating-3-light": "#E7EFB5",
        "rating-3-very-light": "#F6F9E3",
        "rating-2": "#FFD400",
        "rating-2-light": "#FFF4CD",
        "rating-2-very-light": "#FFFCE3",
        "rating-1": "#F39200",
        "rating-1-light": "#FBDEB2",
        "rating-1-very-light": "#FEF5E7",
        "rating-0": "#E30613",
        "rating-0-light": "#FAD3D0",
        "rating-0-very-light": "#FDF1F2",
        "rating-na": "#9D9D9C",
        "rating-na-light": "#D0D0D0",
        "rating-na-very-light": "#EFEFEF",
        "light-green": "#AFCA0B",
        green: "#339737",
        "ff-green": "#1da64a",
        "olive-green": "#3F8342",
        red: "#e30613",
        orange: "#f39200",
        "slk-orange": "#f27c00",
        "localzero-yellow": "#ffc80c",
        "light-blue": "#16bae7",
        "very-light-blue": "#E6F1F5",
        gray: "#505050",
        "mid-gray": "#707070",
        black: "#000000",
        white: "#ffffff",
        "mild-white": "#fbfbfb",
        "stats-dark": "#006e94",
        "stats-light": "#d6f5ff",
        "ranking-dark": "#afca0b",
        "ranking-light": "#f9fde1",
        "solid-black-08": "#ebebeb",
        "solid-black-10": "#e6e6e6",
        "solid-black-20": "#cccccc",
        "solid-black-28": "#b8b8b8",
        "solid-black-40": "#999999",
        "solid-black-50": "#808080",
        "solid-black-70": "#4d4d4d",
        "solid-gray-05": "#f6f6f6",
        "solid-gray-10": "#eeeeee",
        "solid-gray-20": "#dcdcdc",
        "solid-gray-30": "#cbcbcb",
        "solid-gray-40": "#b9b9b9",
        "solid-gray-50": "#a8a8a8",
        "solid-gray-60": "#969696",
        "solid-gray-80": "#737373",
        "solid-light-green-10": "#f7fae7",
        "solid-light-green-15": "#f3f7da",
        "solid-light-green-20": "#eff4ce",
        "solid-light-green-30": "#e7efb6",
        "solid-light-green-40": "#dfea9d",
        "solid-light-green-50": "#d7e585",
        "solid-light-green-70": "#c7da54",
        "solid-ff-green-05": "#f4fbf6",
        "solid-ff-green-10": "#e8f6ed",
        "solid-ff-green-20": "#d2eddb",
        "solid-ff-green-30": "#bbe4c9",
        "solid-ff-green-80": "#4ab86e",
        "solid-green-10": "#ebf5eb",
        "solid-green-20": "#d6ead7",
        "solid-olive-green-10": "#ecf3ec",
        "solid-olive-green-20": "#d9e6d9",
        "solid-olive-green-30": "#c5dac6",
        "solid-rating-4-10": "#e9f6ed",
        "solid-rating-4-60": "#78ca92",
        "solid-rating-4-90": "#34af5c",
        "solid-stats-dark-05": "#f2f8fa",
        "solid-stats-dark-10": "#e6f1f4",
        "solid-stats-dark-20": "#cce2ea",
        "solid-stats-dark-30": "#b3d4df",
        "solid-stats-dark-60": "#66a8bf",
        "solid-stats-dark-80": "#338ba9",
        "solid-stats-white-15": "#2684a4",
        "solid-stats-light-50": "#ebfaff",
        "solid-light-blue-20": "#d0f1fa",
        "solid-light-blue-30": "#b9eaf8",
        "solid-light-blue-60": "#73d6f1",
        "solid-very-light-blue-60": "#f0f7f9",
        "solid-orange-10": "#fef4e6",
        "solid-orange-30": "#fbdeb3",
        "solid-red-05": "#fef3f3",
        "solid-red-10": "#fce6e7",
        "solid-blue-gray-10": "#f0f1f2",
        "solid-blue-gray-25": "#dadcdf",
        "solid-blue-gray-35": "#cbced3",
        "solid-amber50-40": "#fffdf7",
      },
      boxShadow: {
        list: "0 3pt 6pt #00000029",
      },
      height: {
        "58/100": "58%",
        "60/100": "60%",
      },
      width: {
        18: "4.5rem",
        "58/100": "58%",
        "60/100": "60%",
      },
      fontSize: {
        h1: "clamp(1.5rem, 4.69vw, 2rem)",
        h2: "clamp(1.15rem, 3.32vw, 1.5rem)",
        h3: "clamp(1.15rem, 2.93vw, 1.5rem)",
        h4: "clamp(1rem, 2.05vw, 1.5rem)",
      },
      typography: {
        DEFAULT: {
          css: {
            color: "#505050",
            fontFamily: "Inter",
            "font-size": "1rem",
            "line-height": "1.5",
            h1: {
              fontFamily: "Inter",
              "font-size": "clamp(1.5rem, 4.69vw, 2rem)",
              "line-height": "1.5",
              color: "#000000",
              "font-weight": "bold",
            },
            h2: {
              fontFamily: "Inter",
              "font-size": "clamp(1.15rem, 3.32vw, 1.5rem)",
              "line-height": "1.5",
              color: "#000000",
              "font-Weight": "bold",
            },
            h3: {
              fontFamily: "Inter",
              "font-size": "clamp(1.15rem, 2.93vw, 1.5rem)",
              "line-height": "1.5",
              "font-weight": "normal",
              color: "#16bae7",
            },
            h4: {
              fontFamily: "Inter",
              "font-size": "clamp(1rem, 2.05vw, 1.5rem)",
              "line-height": "1.5",
              "font-weight": "normal",
              color: "#1da64a",
            },
            "a:hover": {
              "text-decoration": "underline dotted",
            },
            "a:focus": {
              "text-decoration": "underline dotted",
            },
            "p.note": {
              "font-size": "0.75rem",
            },
          },
        },
      },
    },
  },
  safelist: [
    "bg-rating-na",
    "bg-rating-na-light",
    "bg-rating-na-very-light",
    "bg-rating-0",
    "bg-rating-0-light",
    "bg-rating-0-very-light",
    "bg-rating-1",
    "bg-rating-1-light",
    "bg-rating-1-very-light",
    "bg-rating-2",
    "bg-rating-2-light",
    "bg-rating-2-very-light",
    "bg-rating-3",
    "bg-rating-3-light",
    "bg-rating-3-very-light",
    "bg-rating-4",
    "bg-rating-4-light",
    "bg-rating-4-very-light",
    "border-rating-na",
    "border-rating-0",
    "border-rating-1",
    "border-rating-2",
    "border-rating-3",
    "border-rating-4",
    "text-rating-0",
    "text-rating-1",
    "text-rating-2",
    "text-rating-3",
    "text-rating-4",
    "text-rating-na",
  ],
  plugins: [require("daisyui"), require("@tailwindcss/typography")],
  daisyui: {
    darkTheme: "staedteChallengeDark",
    themes: [
      {
        staedteChallemgeTheme: {
          primary: "#afca0b",
          secondary: "#f27c00",
          accent: "#00aee2",
          neutral: "#707070",
          "base-100": "#ffffff",
          fontFamily: ["Inter", "sans"],
        },
      },
      {
        staedteChallengeDark: {
          primary: "#afca0b",
          secondary: "#f39200",
          accent: "#53d7ff",
          neutral: "#b8c2cc",
          "base-100": "#17212b",
          "base-200": "#101820",
          "base-300": "#2a3947",
          "base-content": "#e7edf1",
          fontFamily: ["Inter", "sans"],
        },
      },
    ],
  },
};
